name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sogajeffrey/pg-restore-rclone:latest --tag  sogajeffrey/pg-restore-rclone:12-alpine
    - name: Login to docker 
      run: docker login -u sogajeffrey -p $DOCKER_TOKEN
      env: 
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
    - name: Push to Docker Hub
      run: docker push sogajeffrey/pg-restore-rclone:latest
    - name: Push to Docker Hub
      run: docker push sogajeffrey/pg-restore-rclone:12-alpine
